---
# Setup for all the master
#
- name: Sanity sleep
  pause: seconds=60

- name: Install calico CNI plugin
  shell: "kubectl apply -f {{ calico_url }}"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: install_calico
  ignore_errors: false
